// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj0i2IQfAB1sbfbV8c0lvsu-CD6rCXDU0',
    appId: '1:817261363837:web:727dc5d92cbd6b4a696714',
    messagingSenderId: '817261363837',
    projectId: 'cj-news-app',
    authDomain: 'cj-news-app.firebaseapp.com',
    storageBucket: 'cj-news-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCudb9UITdPadomM3Hn9eEvbZtygMMkWrg',
    appId: '1:817261363837:android:cd20288a37cda6e4696714',
    messagingSenderId: '817261363837',
    projectId: 'cj-news-app',
    storageBucket: 'cj-news-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUkD_PZkcUqgAzyOpyfQv0RUzsyWXmIiI',
    appId: '1:817261363837:ios:d547b9a667c65673696714',
    messagingSenderId: '817261363837',
    projectId: 'cj-news-app',
    storageBucket: 'cj-news-app.appspot.com',
    iosClientId: '817261363837-dkfdrm1v08lc0chr4v6jv6sj5asuuh43.apps.googleusercontent.com',
    iosBundleId: 'com.example.cjnews',
  );
}
